/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GdMap: typeof import('./src/components/map/gd/gd-map.vue')['default']
    Popup: typeof import('./src/components/map/td-ol/components/popup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TdMap: typeof import('./src/components/map/td/td-map.vue')['default']
  }
}
